language: node_js
node_js:
  - '10'
  - '8'
  - '6'
matrix:
  include:
    - node_js: 10
      env: INTEGRATION=true
script:
  - if [ $INTEGRATION == true ]; then npm run integration; else npm test; fi
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
