name: Labeler

on:
  pull_request:
    types: [opened, edited]
  issues:
    types: [opened, edited]

jobs:
  Label:
    runs-on: ubuntu-latest
    steps:
      - name: Label bugs and enhancements
        uses: fregante/title-to-labels-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Label new rules
        uses: fregante/title-to-labels-action@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          keywords: rule proposal
          labels: new rule, evaluating
