on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          # Locked due to the difference of `zlib.gzipSync()` between Node.js versions
          node-version: 24
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: rm -rf test/snapshots
      # Force update snapshots, https://github.com/avajs/ava/discussions/2754
      - run: npx ava --update-snapshots
        env:
          AVA_FORCE_CI: not-ci
      - run: git add -A
      - run: git commit -m 'Update snapshots' || true
      - run: git push origin
